
/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of ApiResponse
 *
 * @constructor
 */
ApiResponse = function (obj) {
    if(!obj) {
        this.code = null;     
        this.type = null;     
        this.message = null;     
    } else {
        this.code = obj.code;
        this.type = obj.type;
        this.message = obj.message;
    }
};

ApiResponse.prototype = new BaseModel();
ApiResponse.prototype.constructor = ApiResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {int|null}
 */
ApiResponse.prototype.getCode = function() {
    return this.code;
};

/**
 * Setter for Code
 * 
 * @param {int|null} value 
 */
ApiResponse.prototype.setCode = function(value) {
    this.code = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
ApiResponse.prototype.getType = function() {
    return this.type;
};

/**
 * Setter for Type
 * 
 * @param {string|null} value 
 */
ApiResponse.prototype.setType = function(value) {
    this.type = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
ApiResponse.prototype.getMessage = function() {
    return this.message;
};

/**
 * Setter for Message
 * 
 * @param {string|null} value 
 */
ApiResponse.prototype.setMessage = function(value) {
    this.message = value;
};


module.exports = ApiResponse;