
/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of Pet
 *
 * @constructor
 */
Pet = function (obj) {
    if(!obj) {
        this.name = null;     
        this.photoUrls = null;     
        this.id = null;     
        this.category = null;     
        this.tags = null;     
        this.status = null;     
    } else {
        this.name = obj.name;
        this.photoUrls = obj.photoUrls;
        this.id = obj.id;
        this.category = new Category(obj.category);
        this.tags = obj.tags.map(function(model){
            return new Tag(model);
        });
        this.status = obj.status;
    }
};

Pet.prototype = new BaseModel();
Pet.prototype.constructor = Pet;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
Pet.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string} value 
 */
Pet.prototype.setName = function(value) {
    this.name = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
Pet.prototype.getPhotoUrls = function() {
    return this.photoUrls;
};

/**
 * Setter for PhotoUrls
 * 
 * @param {array} value 
 */
Pet.prototype.setPhotoUrls = function(value) {
    this.photoUrls = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {long|null}
 */
Pet.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {long|null} value 
 */
Pet.prototype.setId = function(value) {
    this.id = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {Category|null}
 */
Pet.prototype.getCategory = function() {
    return this.category;
};

/**
 * Setter for Category
 * 
 * @param {Category|null} value 
 */
Pet.prototype.setCategory = function(value) {
    this.category = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array|null}
 */
Pet.prototype.getTags = function() {
    return this.tags;
};

/**
 * Setter for Tags
 * 
 * @param {array|null} value 
 */
Pet.prototype.setTags = function(value) {
    this.tags = value;
};

/**
 * pet status in the store
 *
 * @return {Status6Enum|null}
 */
Pet.prototype.getStatus = function() {
    return this.status;
};

/**
 * Setter for Status
 * 
 * @param {Status6Enum|null} value 
 */
Pet.prototype.setStatus = function(value) {
    this.status = value;
};


module.exports = Pet;