/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */

var Status6Enum = {

    //TODO: Write general description for this element
    AVAILABLE : "available",

    //TODO: Write general description for this element
    PENDING : "pending",

    //TODO: Write general description for this element
    SOLD : "sold"

};

module.exports = Status6Enum;