
/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of Tag
 *
 * @constructor
 */
Tag = function (obj) {
    if(!obj) {
        this.id = null;     
        this.name = null;     
    } else {
        this.id = obj.id;
        this.name = obj.name;
    }
};

Tag.prototype = new BaseModel();
Tag.prototype.constructor = Tag;

/**
 * TODO: Write general description for this method
 *
 * @return {long|null}
 */
Tag.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {long|null} value 
 */
Tag.prototype.setId = function(value) {
    this.id = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
Tag.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string|null} value 
 */
Tag.prototype.setName = function(value) {
    this.name = value;
};


module.exports = Tag;