
/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of User
 *
 * @constructor
 */
User = function (obj) {
    if(!obj) {
        this.id = null;     
        this.username = null;     
        this.firstName = null;     
        this.lastName = null;     
        this.email = null;     
        this.password = null;     
        this.phone = null;     
        this.userStatus = null;     
    } else {
        this.id = obj.id;
        this.username = obj.username;
        this.firstName = obj.firstName;
        this.lastName = obj.lastName;
        this.email = obj.email;
        this.password = obj.password;
        this.phone = obj.phone;
        this.userStatus = obj.userStatus;
    }
};

User.prototype = new BaseModel();
User.prototype.constructor = User;

/**
 * TODO: Write general description for this method
 *
 * @return {long|null}
 */
User.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {long|null} value 
 */
User.prototype.setId = function(value) {
    this.id = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
User.prototype.getUsername = function() {
    return this.username;
};

/**
 * Setter for Username
 * 
 * @param {string|null} value 
 */
User.prototype.setUsername = function(value) {
    this.username = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
User.prototype.getFirstName = function() {
    return this.firstName;
};

/**
 * Setter for FirstName
 * 
 * @param {string|null} value 
 */
User.prototype.setFirstName = function(value) {
    this.firstName = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
User.prototype.getLastName = function() {
    return this.lastName;
};

/**
 * Setter for LastName
 * 
 * @param {string|null} value 
 */
User.prototype.setLastName = function(value) {
    this.lastName = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
User.prototype.getEmail = function() {
    return this.email;
};

/**
 * Setter for Email
 * 
 * @param {string|null} value 
 */
User.prototype.setEmail = function(value) {
    this.email = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
User.prototype.getPassword = function() {
    return this.password;
};

/**
 * Setter for Password
 * 
 * @param {string|null} value 
 */
User.prototype.setPassword = function(value) {
    this.password = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string|null}
 */
User.prototype.getPhone = function() {
    return this.phone;
};

/**
 * Setter for Phone
 * 
 * @param {string|null} value 
 */
User.prototype.setPhone = function(value) {
    this.phone = value;
};

/**
 * User Status
 *
 * @return {int|null}
 */
User.prototype.getUserStatus = function() {
    return this.userStatus;
};

/**
 * Setter for UserStatus
 * 
 * @param {int|null} value 
 */
User.prototype.setUserStatus = function(value) {
    this.userStatus = value;
};


module.exports = User;