/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/15/2016
 */

var configuration = {
    //The base Uri for API calls
    BASEURI : "http://petstore.swagger.io/v2",

    //The OAuth 2.0 access token to be set before API calls
    //TODO: Replace the OAuthAccessToken with an appropriate value
    oAuthAccessToken : "TODO: Replace"

};

module.exports = configuration;
